name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Skopeo
        id: build_skopeo
        run: |
          set -eux
          APP=skopeo
          APP_VERSION=$(cat version.txt)
          APP_REPO="https://github.com/containers/skopeo.git"

          ADD_TAG=""
          tags="$(git ls-remote --tags $APP_REPO | grep 'v[1-9]\.[0-9]*\.[0-9]*$' | awk -F'tags/' '{print $2}' | sort -t. -k1,1n -k2,2n -k3,3n)"
          new_tags="$(printf "%s" "$tags"| sed -n '{/\.0$/{g;p}};h' | tail -4) $(printf "%s" "$tags" | tail -1)"
          echo "::debug::[Tags] $new_tags"

          for t in $new_tags; do
            echo "[check] $t"
            # b=$(echo "${APP_VERSION}" | grep -w ${t} | wc -l)
            b=0
            if [[ $b == 0 ]]; then
              echo "::group::[Build] $t"
              git clone -q --depth=1 --branch $t --progress $APP_REPO
              ls -al .
              pushd ${APP}
              git checkout -b $t $t
              git branch

              ls -al

              brew install gpgme coreutils

              CGO_ENABLE=0 GO111MODULE=on GOOS=darwin GOARCH=arm64 go build -mod=vendor -gcflags '' -tags 'exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp' -o ./bin/skopeo-macos-arm64 ./cmd/skopeo
              md5sum ./bin/skopeo-macos-arm64 > ./bin/skopeo-macos-arm64.md5
              sha256sum ./bin/skopeo-macos-arm64 > ./bin/skopeo-macos-arm64.sha256

              CGO_ENABLE=0 GO111MODULE=on GOOS=darwin GOARCH=amd64 go build -mod=vendor -gcflags '' -tags 'exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp' -o ./bin/skopeo-macos-amd64 ./cmd/skopeo
              md5sum ./bin/skopeo-macos-amd64 > ./bin/skopeo-macos-amd64.md5
              sha256sum ./bin/skopeo-macos-amd64 > ./bin/skopeo-macos-amd64.sha256

              ls -al bin/
              cd ../
              ls -al ./
              ADD_TAG=$t

              echo "::debug::[Push file]"

              echo "${t}" >> version.txt
              git config --global user.email "me@sbg.dev"
              git config --global user.name "Tom Solberg"
              git config --global --add safe.directory /github/workspace
              git add version.txt
              git commit -m "$APP $ADD_TAG (Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`)"
              echo "ADD_TAG=${ADD_TAG}" >> $GITHUB_OUTPUT
              cat ./skopeo/bin/skopeo-macos-{amd64,arm64}.{md5,sha256} > CHECKSUMS.txt
              echo "::endgroup::"
              popd
              break
            else
              echo "::debug::[skip] $t"
            fi
          done
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.build_skopeo.outputs.ADD_TAG != '' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.build_skopeo.outputs.ADD_TAG != '' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: "${{ steps.build_skopeo.outputs.ADD_TAG }}"
          files: |
            ./skopeo/bin/skopeo-macos-amd64
            ./skopeo/bin/skopeo-macos-amd64.md5
            ./skopeo/bin/skopeo-macos-amd64.sha256
            ./skopeo/bin/skopeo-macos-arm64
            ./skopeo/bin/skopeo-macos-arm64.md5
            ./skopeo/bin/skopeo-macos-arm64.sha256
          body_path: ./CHECKSUMS.txt
